"""empty message

Revision ID: 343357551013
Revises: b437cd2c45d6
Create Date: 2022-07-01 22:48:00.186296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343357551013'
down_revision = 'b437cd2c45d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_file', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_file')
    # ### end Alembic commands ###
