"""empty message

Revision ID: 6dc72840d7a4
Revises: 83e9d368e22d
Create Date: 2022-06-15 13:06:51.802060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dc72840d7a4'
down_revision = '83e9d368e22d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('date_posted', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'date_posted')
    # ### end Alembic commands ###
