"""empty message

Revision ID: 83e9d368e22d
Revises: d2e6a4687410
Create Date: 2022-06-15 12:16:05.321533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83e9d368e22d'
down_revision = 'd2e6a4687410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('post', sa.Column('picture', sa.String(length=100), nullable=False))
    op.drop_column('post', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image', sa.VARCHAR(length=100), nullable=False))
    op.drop_column('post', 'picture')
    op.drop_column('post', 'description')
    # ### end Alembic commands ###
