"""empty message

Revision ID: 88984d53dd1f
Revises: cd7607ea943b
Create Date: 2022-06-15 17:00:38.447586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88984d53dd1f'
down_revision = 'cd7607ea943b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('date_posted', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'date_posted')
    # ### end Alembic commands ###
