"""empty message

Revision ID: 97b40e676498
Revises: a308527be4f9
Create Date: 2022-06-15 16:35:39.888741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97b40e676498'
down_revision = 'a308527be4f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('picture', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'picture')
    # ### end Alembic commands ###
