"""empty message

Revision ID: b926f3a13654
Revises: 03e06a7bcf3c
Create Date: 2022-06-15 16:50:40.473842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b926f3a13654'
down_revision = '03e06a7bcf3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('picture', sa.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
